APPLICATION_LANGUAGE = "EN"

APPLICATION_WIDTH = 500
APPLICATION_HEIGHT = 500

APPLICATION_TITLE = "MinimalDo"

APPLICATION_RESIZABLE = False

TODO_LARGE_COLOR = "#FF8080" # pastel red
TODO_MEDIUM_COLOR = "#FFF2AF" # pastel yellow
TODO_SMALL_COLOR = "#AEEA94" # pastel green
